clc; clear; close all;

%% Common Filter Specs
Fs = 12000;          % Sampling frequency
Fp = 2000;           % Passband edge
Fs1 = 3500;          % Stopband edge
Rp = 0.1;            % Passband ripple (dB)
Rs = 40;             % Stopband attenuation (dB)

%% 1. FIR Filter Design (Equiripple, equivalent to fdatool with Parks-McClellan)
firFilt = designfilt('lowpassfir', ...
    'PassbandFrequency', Fp, ...
    'StopbandFrequency', Fs1, ...
    'PassbandRipple', Rp, ...
    'StopbandAttenuation', Rs, ...
    'SampleRate', Fs);

%% 2. IIR Filter Design (Elliptic filter from Part 02)
iirFilt = designfilt('lowpassiir', ...
    'DesignMethod', 'ellip', ...
    'PassbandFrequency', Fp, ...
    'StopbandFrequency', Fs1, ...
    'PassbandRipple', Rp, ...
    'StopbandAttenuation', Rs, ...
    'SampleRate', Fs);

%% Frequency Response Plot
fvtool(firFilt, iirFilt, 'Fs', Fs);
legend('FIR Equiripple', 'IIR Elliptic');
title('Magnitude Response Comparison: FIR vs IIR');

%% Filter Order Comparison
fprintf('FIR filter order: %d\n', firFilt.FilterOrder);
fprintf('IIR filter order: %d\n', iirFilt.FilterOrder);
